targets:
  $default:
    builders:
      #sass_builder|sass_builder:
      #  generate_for: ["*.scss"]
      #  options:
      #    build_extensions:
      #      .scss: [".scss.css"]
      #    ouputStyle: compressed
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          #compiler: dartdevc
          compiler: dart2js
          dart2js_args:
            - --fast-startup
            - --minify
            - --omit-implicit-checks
