targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
          - test/plato_crf_test.dart.browser_test.dart
        options:
          compiler: dartdevc
          #compiler: dart2js
          #dart2js_args:
          #  - --fast-startup
          #  - --minify
          #  - --omit-implicit-checks
