name: plato_angular
description: The Plato Course Request Form, written in AngularDart.
version: 1.0.20180511

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.54.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+11
  angular_components: ^0.9.0-alpha+11
  http: ^0.11.3+16

dev_dependencies:
  angular_test: ^2.0.0-alpha+9
  build_runner: ^0.8.8
  build_test: ^0.10.2+3
  build_web_compilers: ^0.4.0
  mockito: ^2.2.3
  pageloader: ^2.2.6
  sass_builder: ^1.1.2
  test: ^0.12.37
