name: plato_angular
description: A rewrite of the Plato Course Request Form, written in AngularDart.
version: 0.22.20180320

author: Joseph B. Axenroth

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  http: ^0.11.3+13
  sass_builder: 1.1.5

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- sass_builder:
    outputExtension: .scss.css
- angular:
    entry_points: web/main.dart
- $dart2js:
    #minify: true
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
- dart_to_js_script_rewriter

#web:
#  compiler:
#    debug: dartdevc
