name: plato_angular
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: jbaxe2 <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.1
  http: ^0.11.3+13

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- dart_to_js_script_rewriter

#web:
#  compiler:
#    debug: dartdevc
