name: plato_angular
description: A rewrite of the Plato Course Request Form, written in AngularDart.
version: 1.0.20180419

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.1.2 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+10
  angular_components: ^0.9.0-alpha+10
  http: ^0.11.3+16
  sass_builder: 1.2.0

dev_dependencies:
  angular_test: ^2.0.0-alpha+8
  build_runner: ^0.8.2+2
  build_test: ^0.10.1
  build_web_compilers: ^0.3.6
  mockito: ^2.2.2
  pageloader: ^2.2.6
  test: ^0.12.35

#web:
#  compiler:
#    debug: dartdevc
