name: plato_crf
description: The Plato Course Request Form, written in AngularDart.
version: 1.0.20180626

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.65.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+15
  angular_components: ^0.9.0-alpha+15
  http: ^0.11.3+16

dev_dependencies:
  angular_test: ^2.0.0-alpha+13
  build_runner: ^0.8.9
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  mockito: ^3.0.0-beta #^2.2.3
  pageloader: ^3.0.0-alpha #^2.2.6
  sass_builder: ^2.0.2
  test: ^1.0.0 #^0.12.42
