name: plato_crf
description: The Plato Course Request Form, written in AngularDart.
version: 1.0.20180803

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.69.5 <2.0.0'

dependencies:
  angular: ^5.0.0-beta+3
  angular_components: ^0.9.0-beta+2
  http: ^0.11.3+17

dev_dependencies:
  angular_test: ^2.0.0-beta+3
  build_runner: ^0.10.0
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  mockito: ^3.0.0
  pageloader: ^3.0.0-beta
  sass_builder: ^2.1.1
  test: ^1.3.0
