name: plato_crf
description: The Plato Course Request Form, written in AngularDart.
version: 1.0.20180611

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.61.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+13
  angular_components: ^0.9.0-alpha+13
  http: ^0.11.3+16

dev_dependencies:
  angular_test: ^2.0.0-alpha+11
  build_runner: ^0.8.9
  build_test: ^0.10.2+4
  build_web_compilers: ^0.4.0+4
  mockito: ^3.0.0-beta #^2.2.3
  pageloader: ^3.0.0-alpha #^2.2.6
  sass_builder: ^2.0.1
  test: ^0.12.40
