name: plato_angular
description: A rewrite of the Plato Course Request Form, written in AngularDart.
version: 1.0.20180416

author: Joseph B. Axenroth

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  http: ^0.11.3+13
  sass_builder: 1.1.5

dev_dependencies:
  angular_test: ^1.0.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  mockito: ^2.2.2
  test: ^0.12.34

transformers:
- sass_builder:
    outputExtension: .scss.css
- angular:
    entry_points:
    - web/main.dart
    - test/plato_angular_test.dart
- angular/transform/codegen
- angular/transform/reflection_remover:
    $include:
        - test/**_test.dart
- test/pub_serve:
    $include:
        - test/**_test.dart
- $dart2js:
    #minify: true
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
- dart_to_js_script_rewriter

#web:
#  compiler:
#    debug: dartdevc
