name: plato_angular
description: A web app that uses AngularDart Components
version: 0.18.20180306

author: Joseph B. Axenroth

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  http: ^0.11.3+13

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular:
    entry_points: web/main.dart
- $dart2js:
    #minify: true
    commandLineOptions: [--trust-type-annotations, --trust-primitives]
- dart_to_js_script_rewriter

#web:
#  compiler:
#    debug: dartdevc
