name: plato_crf
description: The Plato Course Request Form, written in AngularDart.
version: 1.1.20181002

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.2
  http: ^0.12.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.3
  build_test: ^0.10.3+2
  build_web_compilers: ^0.4.4+1
  mockito: ^3.0.0
  #pageloader: ^3.0.0
  sass_builder: ^2.1.1
  test: ^1.3.3
