name: plato_crf
description: The Plato Course Request Form, written in AngularDart.
version: 1.2.20190201

author: Joseph B. Axenroth

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  http: ^0.12.0+1

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.2.3
  build_test: ^0.10.6
  build_web_compilers: ^1.0.2
  mockito: ^4.0.0
  pageloader: ^3.0.3
  sass_builder: ^2.1.2
  test: ^1.5.3
